<a href="https://colab.research.google.com/github/MAU143429/IA-Laboratorios/blob/Forward/Lab_RedNeuronal_Modificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Autora: Adriana Álvarez F. 
# Since Collab is being used, it is necessary to install Pytorch
import torch as torch

import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm


In [ ]:
def sigmoidalActivationFunction(x):
  return (1/(1+(torch.exp(-x))))


In [ ]:
def forward(weights,featuresT):
  result=weights.mm(featuresT)
  print("RESULT",result)
  return sigmoidalActivationFunction(result)


In [ ]:
def countRows(matrix):
  return matrix.size()[0]

In [ ]:
def countColumns(matrix):
  return matrix.size()[1]

In [ ]:
# Crea una matriz de tamano countHiddenLayer (rows) x countFeatures (columns) 
def randomWeights(rows, colums):
  return (torch.rand(rows, colums))


In [ ]:
x = torch.tensor([[0.05, 0.01], [0.02, 0.5], [2,4]])
rows=countRows(x) # corresponde a la cantidad de observaciones del dataset, es decir, a la cantidad de observaciones
columns=countColumns(x) #corresponde a la cantidad de features del dataset
countNeuronsHiddenLayer1=1
weights=randomWeights(countNeuronsHiddenLayer1, columns)
#print(weights)
featuresT=x.transpose(0,1)
#print(featuresT)
r = forward(weights,featuresT)
print(r)


tensor([[0.4584, 0.8081]])
tensor([[0.0500, 0.0200, 2.0000],
        [0.0100, 0.5000, 4.0000]])
RESULT tensor([[0.0310, 0.4132, 4.1491]])
tensor([[0.5078, 0.6019, 0.9845]])


# Lab – Red neuronal Forward


*   Mauricio Calderon
*   Mario Araya


1. Explique que significa el resultado que se imprime en r.

2. Explique el resultado si agrega una observación adicional al dataset. Debe mostrar el dataset
modificado.

3. Explique el resultado si agrega una característica adicional al dataset. Debe mostrar el dataset
modificado.

4. Modifique el código para agregar una nueva neurona a la capa oculta 1. Incluya un dibujo de la
red.

5. Modifique el código para agregar la programación del bias.

6. Sobre el punto anterior, modifique el código para agregar una nueva capa oculta 2 con 1
neurona. Incluya un dibujo de la red.

7. Sobre el punto anterior, modifique el código para agregar una nueva neurona a la capa oculta 2.
Incluya un dibujo de la red.

8. Programe la red neuronal del punto anterior sin utilizar métodos ya preexistentes, es decir,
programe todo el algoritmo (sólo el forward). Debe usar operaciones con matrices y un mínimo
de fors. Prográmelo de forma que sea parametrizable en la cantidad de observaciones y de
features.

9. Agregue el target y la programación de la función de error para el primer forward.