<a href="https://colab.research.google.com/github/MAU143429/IA-Laboratorios/blob/updated/LabPerceptr%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio - Perceptrón

*   Mauricio Calderón
*   Mario Araya





1. Programe el algoritmo del perceptrón genérico que reciba cualquier set de datos 

In [ ]:
import numpy as np

class Perceptron:
    def __init__(self, learning_rate=0.01, max_iter=100):
        self.learning_rate = learning_rate
        self.max_iter = max_iter
    
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        for i in range(self.max_iter):
            y_pred = np.dot(X, self.weights) + self.bias
            y_pred = np.where(y_pred > 0, 1, -1)
            if np.array_equal(y_pred, y):
                print(f"Converged in {i+1} iterations")
                break
            else:
                error = y - y_pred
                self.weights += self.learning_rate * np.dot(X.T, error)
                self.bias += self.learning_rate * np.sum(error)
    
    def predict(self, X):
        y_pred = np.dot(X, self.weights) + self.bias
        y_pred = np.where(y_pred > 0, 1, -1)
        return y_pred

2. Ejecute el programa con un set de datos de al menos 1000 observaciones y 3 características

In [ ]:
import numpy as np
from sklearn import datasets

# Establecer la semilla aleatoria para reproducibilidad
np.random.seed(42)

# Generar un conjunto de datos aleatorios con 1000 observaciones y 3 características lineales
x1 = np.linspace(-1, 1, 1000)
x2 = np.linspace(0, 2, 1000)
x3 = np.linspace(1, 3, 1000)
dataset = np.column_stack((x1, x2, x3))

# Agregar ruido aleatorio a las características
dataset += np.random.normal(size=dataset.shape)

print(dataset)

perceptron = Perceptron(learning_rate=0.1, max_iter=100)
perceptron.fit(dataset, newY)

# nuevos datos
X_test = np.array([[5, 6], [2, 1]])

print(X_test)
# hacer predicciones
y_pred = perceptron.predict(X_test)
print(y_pred)

[[-0.50328585 -0.1382643   1.64768854]
 [ 0.52503186 -0.23215137  0.76786505]
 [ 0.58321682  0.77143873  0.53452962]
 ...
 [ 1.59811432  2.06803286  2.78378703]
 [ 0.04607954  2.07547852  3.25575054]
 [-0.24176058  2.33417642  2.84474095]]


ValueError: ignored

3. Gráfique los datos del punto 2 con un plano que evidencie la separación de los datos y las observaciones